name: Check links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Check for broken Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
